name: flutter_app_core
description: Reusable methods and widgets for building apps 
version: 1.12.0
homepage:

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^4.8.5
  cloud_functions: ^4.4.0
  cupertino_icons: ^1.0.5
  dio: ^5.3.2
  firebase_analytics: ^10.4.5
  firebase_auth: ^4.7.3
  firebase_core: ^2.15.1
  firebase_core_web: ^2.7.0
  firebase_crashlytics: ^3.3.5
  firebase_dynamic_links: ^5.3.5
  firebase_messaging: ^14.6.6
  firebase_storage: ^11.2.6
  flutter_app_badger: ^1.5.0
  flutter_keyboard_visibility: ^5.4.1
  flutter_libphonenumber: 1.1.0
  flutter_riverpod: ^2.3.7
  freezed_annotation: ^2.4.1
  google_fonts: ^5.1.0
  google_mobile_ads: ^3.0.0 
  google_sign_in: ^6.1.4
  go_router: ^10.1.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  json_annotation: ^4.8.1
  modal_bottom_sheet: ^3.0.0-pre
  numberpicker: ^2.1.2
  path_provider: ^2.1.0
  pinput: ^3.0.0
  purchases_flutter: ^5.6.2
  quiver: ^3.2.1
  riverpod_annotation: ^2.1.2
  stack_trace: ^1.10.1
  the_apple_sign_in: ^1.1.1
  url_launcher: ^6.1.12
  visibility_detector: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  custom_lint: ^0.5.2
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  riverpod_generator: ^2.2.6
  riverpod_lint: ^2.0.1